spring:
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: "false"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  oauth2:
    google:
      client-id: 36630242297-dlq71h1k3vjocp2ai6i902uuu0lg4273.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: https://a508.co.kr/api/user/login/google
      token-uri: https://oauth2.googleapis.com/token
      resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

  api:
    base:
      url: https://www.greenproduct.go.kr/open-api/open-api/rest/GreenProductInformationInquiryService2.do
    cert:
      key: b7c7f3a73086bec7f2f39445f24e478cfbc8068389d38f66a1848c5c062f128f

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      # 나중에 다시 none으로 바꾸기
#      ddl-auto: create
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mariadb://a508.co.kr:3306/knocknock
    username: root
    password: knocknock
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true

  redis:
    host: redis
#    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587           # SMTP 서버 포트
    username: knocknock.welcome@gmail.com # SMTP 서버 로그인 아이디(이메일의 앞부분)
    password: 'hgxzaslvrpbkfphz'
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부(기본값: FALSE)
          starttls:
            enable: true
            trust: smtp.gmail.com

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    org:
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE
      spring.boot: DEBUG
      spring.security: DEBUG
      spring.web: DEBUG
      apache.tiles: INFO
    root: INFO
    com.samsung.security: DEBUG
  file:
    name: /var/jenkins_home/util/knock/back/ssafy-web.log
server:
  error:
    include-exception: false     # Response 에 Exception 을 표시할지
    include-message: always      # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
  port: 8083
  forward-headers-strategy: native

jwt:
  issuer: knocknockservice
  secret_key: +Oijz4jS1qr6TEmDaEBkwUBKTFZz7UvFyAzUElZOlZ+nPskEZyx/EsLFNhdz1kjBmjw=
  access_expiration_ms: 10000000
  refresh_expiration_ms: 2592000000

cors:
  front_url: "*"

# swagger 관련
springfox:
  documentation:
    swagger:
      use-model-v3: false
